### ISSUE TITLE
ResponseContent status property usage incorrect

### ISSUE THREAD

**Issue by petertuton** [Azure-Samples/active-directory-dotnet-external-identities-api-connector-azure-function-validate#4]
The `ResponseContent` class's `status` property should be an `int`, as per [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector#example-of-a-validation-error-response).

Additionally, calls using the `ResponseContent` constructor within a `BadRequestObjectResult` constructor that don't pass the 400 status (in `SignUpValidation.cs`, lines 51, 60, 66) results in AzureAD B2C returning a generic "Bad Request" message instead of the message used in the code. The 400 status should be passed (or make it the default value).

**Comment by yoelhor** [comment]
Dear @petertuton,

Thanks for the feedback.  The status code can be type of string or int (I'm updating the document). The issue is due to a condition that causes the API to return null, instead of 400. For more information, see the PR. This GitHub issue will be closed automatically. If you have any questions or need further information, please open new GitHub issue.

Yoel
